"""empty message

Revision ID: 236db90e6f66
Revises: ad9d95139c0c
Create Date: 2022-08-08 19:41:47.329470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236db90e6f66'
down_revision = 'ad9d95139c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite__characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('charcter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charcter_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite__planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('favorites', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favorites')
    op.drop_table('favorite__planets')
    op.drop_table('favorite__characters')
    # ### end Alembic commands ###
