"""empty message

Revision ID: 684d1a33970b
Revises: 236db90e6f66
Create Date: 2022-08-08 19:43:55.320825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '684d1a33970b'
down_revision = '236db90e6f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorites', mysql.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
