"""empty message

Revision ID: f37f997bf3fa
Revises: 8b348cb5fa6c
Create Date: 2022-08-05 14:46:37.589135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37f997bf3fa'
down_revision = '8b348cb5fa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('eye_color', sa.String(length=256), nullable=False),
    sa.Column('gender', sa.String(length=256), nullable=False),
    sa.Column('hair_color', sa.String(length=256), nullable=False),
    sa.Column('height', sa.String(length=256), nullable=False),
    sa.Column('weight', sa.String(length=256), nullable=False),
    sa.Column('complexion', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
